#version 430 core

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
// 1x pro zeile

struct tile
{
  uint heights[4];
};

layout(binding = 0, std430) buffer data 
{
  tile tiles[];
};

uniform uint width;
uniform uint hashValue;
uniform vec3 sunDir;
uniform bool meltSnow;
uniform bool evaporateWater;
uniform bool rain;

uint height_from_idx(uint idx)
{
  uint mask = 0xFFFF;
  uint height = 0;

  for (uint i = 0; i < 4; i++)
  {
    height += tiles[idx].heights[i] & mask;
    height += tiles[idx].heights[i] >> 16;
  }

  return height;
}

const uint phi = 0x61C88647;

uint pcg_hash(uint x)
{
  uint state = x * 747796405u + 2891336453u;
  uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
  return (word >> 22u) ^ word;
}

uint hash(uint x, uint y, uint v)
{
  return pcg_hash(((x * phi + y) * phi + v) * phi);
}

void main()
{
  // TODO clean up & use texture
  uint lineIdx = gl_GlobalInvocationID.x;
  uint mask = 0xFFFF;

  for (uint i = lineIdx * width; i < (lineIdx + 1) * width; i++)
  {
    tile currentTile = tiles[i];
    uint waterHeight = currentTile.heights[0] >> 16;
    uint snowHeight = currentTile.heights[0] & mask;

    if (meltSnow)
    {
      if (snowHeight > 0)
      {
        uint meltAmount = max(uint(snowHeight * 0.02), 1); // max snowheight = 100

        uint loVal = ~meltAmount + 1;
        uint hiVal = (meltAmount - 1) << 16;
        uint val = hiVal | (loVal & mask);
        atomicAdd(tiles[i].heights[0], val);
      }
    }

    if (evaporateWater)
    {
      if (waterHeight > 0)
      {
        uint val = (~1 + 1) << 16;
        atomicAdd(tiles[i].heights[0], val);
      }
    }
    
    if (!meltSnow && !evaporateWater)
    {
      uint topIdx = i - width;
      uint bottomIdx = i + width;
      uint leftIdx = i - 1;
      uint rightIdx = i + 1;

      float yDiff = (float(height_from_idx(topIdx)) - float(height_from_idx(bottomIdx))) * 0.5;
      float xDiff = (float(height_from_idx(rightIdx)) - float(height_from_idx(leftIdx))) * 0.5;
      vec3 normal = normalize(vec3(xDiff, yDiff, 100 /* factor from vertex shader */));

      const uint maxHeight = 13000;
      float height = clamp(float(height_from_idx(i)) - 10000, float(0), float(maxHeight));

      const float minTemp = -10;
      const float maxTemp = 22;
      const float sunMaxTemp = 8;

      float temp = mix(minTemp, maxTemp, 1 - height * (1.0 / maxHeight));
      float sunAllignment = dot(normal, sunDir);

      if (sunAllignment > 0)
        temp += sunAllignment * sunMaxTemp;

      if (rain)
      {
        uint rand = hash(i - (lineIdx * width), lineIdx, hashValue);

        if ((rand & 3) <= 1)
        {
          uint addVal = rand & 4;

          if (temp > 0)
            atomicAdd(tiles[i].heights[0], addVal << 16);
          else
            atomicAdd(tiles[i].heights[0], addVal);
        }
      }

      if (temp <= 0)
        continue;
      
      if (snowHeight > 0)
      {
        uint meltAmount = 1;

        if (temp > 10)
          meltAmount = 3;
        if (temp > 3)
          meltAmount = 2;
        
        meltAmount = clamp(meltAmount, 0, snowHeight); // todo make this pretty

        uint loVal = ~meltAmount + 1;
        uint hiVal = (meltAmount - 1) << 16;
        uint val = hiVal | (loVal & mask);
        atomicAdd(tiles[i].heights[0], val);
      }
      else if (waterHeight > 0)
      {
        uint evaporation = 1;

        if (temp > 20)
          evaporation = 2;
        //if (temp > 15)
        //  evaporation = 2;

        evaporation = clamp(evaporation, 0, waterHeight); // todo make this pretty

        uint val = (~evaporation + 1) << 16;
        atomicAdd(tiles[i].heights[0], val);
      }

      // TODO melt snow... & turn rain into snow & maybe turn water into snow, when too cold
    }
  }
}
