#version 430 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
// 1x pro zeile

struct tile
{
  uint heights[4];
};

layout(binding = 0, std430) buffer data 
{
  tile tiles[];
};

uniform uint width;

void main()
{
  uint lineIdx = gl_GlobalInvocationID.x; // maybe needs to be the work group id?

  // add water
  for (uint i = lineIdx * width; i < (lineIdx + 1) * width; i++)
  {
    tiles[i].heights[0] += 1; 
  }

  // take terrain with you / away (atomic adds)

  // add water to lowest neighbour (atomic adds)
}
