#version 430 core

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
// 1x pro zeile

struct tile
{
  uint heights[4];
};

layout(binding = 0, std430) buffer data 
{
  tile tiles[];
};

uniform uint width;

uint mask = 0xFFFF;

void addTerrain(uint index, uint amount, uint terrainType)
{
  uint val = amount;

  if ((terrainType & 1) == 0)
    val <<= 16;
  
  atomicAdd(tiles[index].heights[terrainType / 2], val);
}

void removeTerrain(uint index, uint amount, uint terrainType)
{
  uint val = (~amount + 1);

  if ((terrainType & 1) == 0)
    val <<= 16;

  atomicAdd(tiles[index].heights[terrainType / 2], val);
}

const ivec2 neighbours[8] = ivec2[8](ivec2(-1, -1), ivec2(-1, 0), ivec2(-1, 1), ivec2(0, -1), ivec2(0, 1), ivec2(1, -1), ivec2(1, 0), ivec2(1, 1));

void main()
{
  uint lineIdx = gl_GlobalInvocationID.x;
  uint y = lineIdx;
  uint offset = lineIdx * width;

  // todo change per frame which neighbour to choose if all are the same height

  for (uint x = 0; x < width; x++)
  {
    // do we have water? if no? skip.      
    tile self = tiles[offset + x];
    uint selfWater = self.heights[0] >> 16;

    if (selfWater == 0)
      continue;

    ivec2 selfPos = ivec2(x, y);

    uint minNeighbor = 0;
    uint minNeighborHeight = 1 << 24;

    for (uint i = 0; i < 8; i++)
    {
      ivec2 tilePos = selfPos + neighbours[i];

      if (tilePos.x < 0 || tilePos.y < 0 || tilePos.x > width - 1 || tilePos.y > width - 1)
        continue;

      // get tile
      uint tileIdx = tilePos.y * width + tilePos.x;
      tile t = tiles[tileIdx];

      // calc height
      uint height = 0; 

      for (uint j = 0; j < 4; j++)
      {
        height += t.heights[j] & mask;
        height += t.heights[j] >> 16;
      }

      // is height smaller?
      if (height < minNeighborHeight)
      {
        minNeighborHeight = height;
        minNeighbor = tileIdx;
      }  
    }

    // cmp with min Neighbor height, if lower -> add half of diff to it.
    uint height = 0; 

    for (uint i = 0; i < 4; i++)
    {
      height += self.heights[i] & mask;
      height += self.heights[i] >> 16;
    }

    if (height > minNeighborHeight)
    {
      uint diff = min((height - minNeighborHeight) / 2, selfWater);

      uint removeVal = (~diff + 1) << 16;
      atomicAdd(tiles[offset + x].heights[0], removeVal);

      uint addVal = diff << 16;
      atomicAdd(tiles[minNeighbor].heights[0], addVal);
    }
  }
}
