#version 430 core

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
// 1x pro zeile

struct tile
{
  uint heights[4];
};

layout(binding = 0, std430) buffer data 
{
  tile tiles[];
};

uniform uint width;

uint mask = 0xFFFF;

void addTerrain(uint index, uint amount, uint terrainType)
{
  uint val = amount;

  if ((terrainType & 1) == 0)
    val <<= 16;
  
  // todo max val at 2^16
  atomicAdd(tiles[index].heights[terrainType / 2], val);
}

void removeTerrain(uint index, uint amount, uint terrainType)
{
  uint val = (~amount + 1);

  if ((terrainType & 1) == 0)
    val <<= 16;

  // todo clamp with 0
  atomicAdd(tiles[index].heights[terrainType / 2], val);
}

void main()
{
  uint lineIdx = gl_GlobalInvocationID.x;

  // add water to lowest neighbour (atomic adds) // change per frame which neighbour to choose if all are the same height
  for (uint i = lineIdx * width; i < (lineIdx + 1) * width; i++)
  {
    
  }
}
