#version 430 core

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
// 1x pro zeile

struct tile
{
  uint heights[4];
};

layout(binding = 0, std430) buffer data 
{
  tile tiles[];
};

uniform uint width;
uniform uint hashValue;

const uint mask = 0xFFFF;

void addTerrain(uint index, uint amount, uint terrainType)
{
  uint val = amount;

  if ((terrainType & 1) == 1)
    val <<= 16;
  
  atomicAdd(tiles[index].heights[terrainType / 2], val);
}

void removeTerrain(uint index, uint amount, uint terrainType)
{
  uint val = (~amount + 1);

  if ((terrainType & 1) == 1)
    val <<= 16;

  atomicAdd(tiles[index].heights[terrainType / 2], val);
}

const uint phi = 0x61C88647;

uint pcg_hash(uint x)
{
  uint state = x * 747796405u + 2891336453u;
  uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
  return (word >> 22u) ^ word;
}

uint hash(uint x, uint y, uint v)
{
  return pcg_hash(((x * phi + y) * phi + v) * phi);
}

const ivec2 neighbours[8] = { ivec2(-1, -1), ivec2(-1, 0), ivec2(-1, 1), ivec2(0, -1), ivec2(0, 1), ivec2(1, -1), ivec2(1, 0), ivec2(1, 1) };

void main()
{
  uint lineIdx = gl_GlobalInvocationID.x;
  uint y = lineIdx;
  uint offset = lineIdx * width;

  for (uint x = 0; x < width; x++)
  {    
    tile self = tiles[offset + x];
    uint selfWater = self.heights[0] >> 16;

    // do we have water? if no? skip.
    if (selfWater == 0 || (hash(x, y, hashValue) & 15) <= 3)
      continue;

    ivec2 selfPos = ivec2(x, y);

    uint minNeighbor = 0;
    uint minNeighborHeight = 1 << 24;

    for (uint i = 0; i < 8; i++)
    {
      ivec2 tilePos = selfPos + neighbours[i];

      if (tilePos.x < 0 || tilePos.y < 0 || tilePos.x >= width || tilePos.y >= width)
        continue;

      // get tile
      uint tileIdx = tilePos.y * width + tilePos.x;
      tile t = tiles[tileIdx];

      // calc height
      uint height = 0; 

      for (uint j = 0; j < 4; j++)
      {
        height += t.heights[j] & mask;
        height += t.heights[j] >> 16;
      }

      // is height smaller?
      if (height < minNeighborHeight)
      {
        minNeighborHeight = height;
        minNeighbor = tileIdx;
      }  
    }

    // cmp with min Neighbor height, if lower -> add half of diff to it.
    uint height = 0; 

    for (uint i = 0; i < 4; i++)
    {
      height += self.heights[i] & mask;
      height += self.heights[i] >> 16;
    }

    if (height > minNeighborHeight)// && (hash(x, y, hashValue) & 8) <= 7)
    {
      uint idx = offset + x;

      // get highest terrain at own tile (underneath water)
      uint terrainTypeBeneath = 0;

      for (uint i = 1; i < 4; i++)
      {
        if ((self.heights[i] & mask) > 0)
        {
          terrainTypeBeneath = i * 2;
          break;
        }
        else if ((self.heights[i] >> 16) > 0)
        {
          terrainTypeBeneath = i * 2 + 1;
          break;
        }
      }

      uint diff = min((height - minNeighborHeight) / 2, selfWater);

      if (terrainTypeBeneath > 0 && diff > 1 && terrainTypeBeneath != 7)
      {
        removeTerrain(idx, 1, terrainTypeBeneath);
        addTerrain(minNeighbor, 1, terrainTypeBeneath);
      }

      uint removeVal = (~diff + 1) << 16;
      atomicAdd(tiles[idx].heights[0], removeVal);

      uint addVal = diff << 16;
      atomicAdd(tiles[minNeighbor].heights[0], addVal);
    }
  }
}
