#version 430 core

// 1x pro zeile
layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct tile
{
  uint heights[4];
};

layout(binding = 0, std430) buffer data 
{
  tile tiles[];
};

uniform uint width;
uniform uint hashValue;

const uint mask = 0xFFFF;
const uint phi = 0x61C88647;

uint pcg_hash(uint x)
{
  uint state = x * 747796405u + 2891336453u;
  uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
  return (word >> 22u) ^ word;
}

uint hash(uint x, uint y, uint v)
{
  return pcg_hash(((x * phi + y) * phi + v) * phi);
}

void main()
{
  uint lineIdx = gl_GlobalInvocationID.x;
  uint y = lineIdx;
  uint offset = lineIdx * width;

  for (uint x = 0; x < width; x++)
  {
    uint rand = hash(x, y, hashValue);

    if ((rand & 3) <= 1)
    {
      uint addVal = (rand & 4) << 16;
      atomicAdd(tiles[offset + x].heights[0], addVal);
    }
  }
}
