#version 430 core

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct tile
{
  uint heights[4];
};

layout(binding = 0, std430) buffer data 
{
  tile tiles[];
};

uniform layout(binding = 0, r8) image2D texture;

uniform float lerpFactor;
uniform uint width;
uniform uint textureWidth;
uniform vec3 sunDir;

uint height_from_idx(uint idx)
{
  uint mask = 0xFFFF;
  uint height = 0;

  for (uint i = 0; i < 4; i++)
  {
    height += tiles[idx].heights[i] & mask;
    height += tiles[idx].heights[i] >> 16;
  }

  return height;
}

void main()
{
  const uint y = gl_GlobalInvocationID.x;
  const uint offset = y * textureWidth;

  for (uint x = 0; x < textureWidth; x++)
  {
    ivec2 texCoord = ivec2(x, y);

    // sample height & normals for average
    uvec2 samplePos = texCoord * uvec2(8, 8);
    uvec2 samplePosTop = samplePos + uvec2(4, 2);
    uvec2 samplePosRight = samplePos + uvec2(6, 4);
    uvec2 samplePosBottom = samplePos + uvec2(4, 6);
    uvec2 samplePosLeft = samplePos + uvec2(2, 4);

    uint heightTop = height_from_idx(samplePosTop.y * width + samplePosTop.x);
    uint heightRight = height_from_idx(samplePosRight.y * width + samplePosRight.x);
    uint heightBottom = height_from_idx(samplePosBottom.y * width + samplePosBottom.x);
    uint heightLeft = height_from_idx(samplePosLeft.y * width + samplePosLeft.x);

    uint avgHeight = (heightTop + heightRight + heightBottom + heightLeft) / 4;

    float yDiff = (float(heightTop) - float(heightBottom)) * 0.5; // is this an accaptable approximation
    float xDiff = (float(heightRight) - float(heightLeft)) * 0.5;
    vec3 avgNorm = normalize(vec3(xDiff, yDiff, 100));

    // calc temp
    const float minTemp = -7;
    const float maxTemp = 22;
    const float sunMaxTemp = 8;

    const uint maxHeight = 13000;
    float height = clamp(float(avgHeight) - 10000, float(0), float(maxHeight));

    float temp = mix(minTemp, maxTemp, 1 - height * (1.0 / maxHeight));
    float sunAllignment = dot(avgNorm, sunDir);

    if (sunAllignment > 0)
      temp += sunAllignment * sunMaxTemp;

    // mix with last temp
    float lastTemp = imageLoad(texture, texCoord).x;
    temp = mix(temp, lastTemp, lerpFactor);

    // set new temp
    imageStore(texture, texCoord, vec4(temp, 0, 0, 0));
  }
}
