#version 430 core

// 1x pro zeile
layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct tile
{
  uint heights[4];
};

layout(binding = 0, std430) buffer data 
{
  tile tiles[];
};

uniform sampler2d texture;

uniform uint width;
uniform vec3 sunDir;
uniform float factor; // i think

const uint mask = 0xFFFF;

uint height_from_idx(uint idx)
{
  uint mask = 0xFFFF;
  uint height = 0;

  for (uint i = 0; i < 4; i++)
  {
    height += tiles[idx].heights[i] & mask;
    height += tiles[idx].heights[i] >> 16;
  }

  return height;
}

void main()
{
  uint y = gl_GlobalInvocationID.x;
  uint offset = y * width;

  for (x = 0; x < width; x++)
  {
    tile self = tiles[offset + x];

    uint topIdx = _index - width;
    uint bottomIdx = _index + width;
    uint leftIdx = _index - 1;
    uint rightIdx = _index + 1;

    float yDiff = (float(height_from_idx(topIdx)) - float(height_from_idx(bottomIdx))) * 0.5;
    float xDiff = (float(height_from_idx(rightIdx)) - float(height_from_idx(leftIdx))) * 0.5;
    vec3 normal = normalize(vec3(xDiff, yDiff, 100 /* factor from vertex shader */));

    uint height = height_from_idx(self);

    float minTemp = -10;
    float maxTemp = 30;
    float sunMaxTemp = 10;

    float temp = mix(minTemp, maxTemp, clamp(height * 0.0032, 0, 1));
    float sunAllignment = dot(normal, sunDir);

    if (sunAllignment > 0)
      temp += sunAllignment * sunMaxTemp;

    // TODO lerp with old temp
    // TODO evaporate via temp
  } 
}
