#version 430 core

// 1x pro zeile
layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct tile
{
  uint heights[4];
};

layout(binding = 0, std430) buffer data 
{
  tile tiles[];
};

uniform sampler2d texture;

uniform uint width;
uniform float sunAngle;
uniform float factor; // i think

const float pi = 3.1415926;
const uint mask = 0xFFFF;

void main()
{
  uint y = gl_GlobalInvocationID.x;
  uint offset = y * width;

  for (x = 0; x < width; x++)
  {
    tile self = tiles[offset + x];

    uint height = 0;
    for (uint i = 0; i < 4; i++)
    {
      height += self.heights[i] & mask;
      height += self.heights[i] >> 16;
    }

    // at 5km -10C in winter at night, 3C in summer at night
    // at 5km -8C in winter at day, 8C in summer at day
    // at 0m 0 in winter at night, 20 in summer at night
    // at 0m 10 in winter at day, 35 in summer at night

    if (sunAngle > 0 && sunAngle < pi)
    {
      // in sunlight
    }
    else
    {
      // in shade
    }
  } 
}
