#version 430 core

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

uniform layout(r8, binding = 0) image2D tempTex;
uniform layout(r8, binding = 1) image2D velocityTex;
uniform uint texWidth;

void main()
{
  const uint y = gl_GlobalInvocationID.x;
  const vec2 generellDir = vec2(1, 0);

  for (uint x = 0; x < texWidth; x++)
  { 
    ivec2 texCoord = ivec2(x, y);

    // read density in own cell
    float selfTemp = imageLoad(tempTex, texCoord).x;

    // read density in cell of wind dir
    ivec2 nextCellCoord = texCoord + ivec2(generellDir);

    if (nextCellCoord.x >= texWidth || nextCellCoord.y >= texWidth)
      continue;
    
    float nextTemp = imageLoad(tempTex, nextCellCoord).x;

    // adapt wind speed according to density:
    float tempDiff = nextTemp - selfTemp;
    // density in next cell higher (= temp lower): slow down - lower density / increase temperature in next cell
    // density in next cell lower (= temp higher): speed up - increase density / decrease temperature in next cell
    float newTemp = clamp(nextTemp - tempDiff * 0.5, 0, 1); // balance temperature (density)
    float vel = imageLoad(velocityTex, texCoord).x;
    float newVel = clamp(vel + tempDiff * 0.5 /*idk man*/, 0, 1);

    imageStore(tempTex, nextCellCoord, vec4(newTemp, 0, 0, 0)); // TODO atomic?
    imageStore(velocityTex, texCoord, vec4(newVel, 0, 0, 0)); // TODO atomic?

    // else: stay the same 

    // TODO: height - adapt height according to terrain, adapt height according to air density
  }
}
