#version 430 core

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct tile
{
  uint heights[4];
};

layout(binding = 0, std430) buffer data 
{
  tile tiles[];
};

uniform layout(rgba32f) image2D windTex; // vel.x, vel.y, height, air temp
uniform uint terrainWidth;

const uint mask = 0xFFFF;

uint height_from_idx(uint idx)
{
  uint height = 0;

  for (uint i = 0; i < 4; i++)
  {
    height += tiles[idx].heights[i] & mask;
    height += tiles[idx].heights[i] >> 16;
  }

  return height;
}

void addTerrain(uint index, uint amount, uint terrainType)
{
  uint val = amount;

  if ((terrainType & 1) == 1)
    val <<= 16;
  
  atomicAdd(tiles[index].heights[terrainType / 2], val);
}

void removeTerrain(uint index, uint amount, uint terrainType)
{
  uint val = (~amount + 1);

  if ((terrainType & 1) == 1)
    val <<= 16;

  atomicAdd(tiles[index].heights[terrainType / 2], val);
}

vec4 interpolate_wind(uvec2 pos)
{
  const ivec2 maxTexWidth = ivec2(terrainWidth / 4 - 1);

  vec2 fTexPos = max(vec2(pos) / vec2(4.0) - vec2(0.5), vec2(0, 0));
  ivec2 texPos = ivec2(fTexPos);

  vec4 tSelf = imageLoad(windTex, texPos);
  vec4 tRight = imageLoad(windTex, min(texPos + ivec2(1, 0), maxTexWidth));
  vec4 tBottom = imageLoad(windTex, min(texPos + ivec2(0, 1), maxTexWidth));
  vec4 tBottomRight = imageLoad(windTex, min(texPos + ivec2(1, 1), maxTexWidth));
  
  vec2 fac = mod(fTexPos, 1.0);
  
  vec4 top = mix(tSelf, tRight, fac.x);
  vec4 bottom = mix(tBottom, tBottomRight, fac.x);
  vec4 total = mix(top, bottom, fac.y);

  return total;
}

void main()
{
  uint lineIdx = gl_GlobalInvocationID.x;
  uint y = lineIdx;
  uint offset = lineIdx * terrainWidth;

  for (uint x = 0; x < terrainWidth; x++)
  {
    uint selfIndex = offset + x;

    ivec2 windTexCoord = ivec2(x / 4, y / 4);
    vec4 windData = interpolate_wind(uvec2(x, y));

    if (windData.z - height_from_idx(selfIndex) > 4) // wind too high
      continue;

    vec2 windDir = windData.xy * 20;

    if (dot(windDir, windDir) < 1) // wind not strong enough to carry to another tile
      continue;

    float particleHeight = max(windData.z, height_from_idx(selfIndex));
    ivec2 targetTilePos = ivec2(x, y) + ivec2(windDir);
    uint targetTileIdx = targetTilePos.y * terrainWidth + targetTilePos.x;
    uint targetTileHeight = height_from_idx(targetTileIdx);
    
    bool outOfBounds = targetTilePos.x < 0 && targetTilePos.y < 0 && targetTilePos.x > terrainWidth - 1 && targetTilePos.y > terrainWidth - 1;

    while (particleHeight > float(targetTileHeight) && !outOfBounds)
    {
      particleHeight -= 0.1;
      windDir *= 0.95; // slow down over time

      if (dot(windDir, windDir) < 1)
        break;

      targetTilePos += ivec2(windDir);
      targetTileIdx = targetTilePos.y * terrainWidth + targetTilePos.x;
      targetTileHeight = height_from_idx(targetTileIdx);

      if (targetTilePos.x < 0 && targetTilePos.y < 0 && targetTilePos.x > terrainWidth - 1 && targetTilePos.y > terrainWidth - 1)
        outOfBounds = true;
    }

    uint highestTerrainType = 0;
    uint layerHeight = 0;
    tile selfTile = tiles[selfIndex];

    for (uint i = 0; i < 4; i++)
    {
      uint height = selfTile.heights[i];

      if ((height & mask) > 0)
      {
        highestTerrainType = i * 2;
        layerHeight = height & mask;
        break;
      }
      else if ((height >> 16) > 0)
      {
        highestTerrainType = i * 2 + 1;
        layerHeight = height >> 16;
        break;
      }
    }
    
    if (highestTerrainType == 7 /*bedrock*/)
      continue;

    float windStrengthScaled = clamp(length(windData.xy) * 12, 0, 1);
    uint diff = min(layerHeight, uint(5.0 * windStrengthScaled)); // TODO check above only the height + this (when setting the particles)

    removeTerrain(selfIndex, diff, highestTerrainType);

    if (!outOfBounds)
      addTerrain(targetTileIdx, diff, highestTerrainType);
  }
  // it seems like terrain gets stuck on something, then this rises and then even more terrain gets stuck there - maybe an issue of adding all the terrain to one tile instead of spreading it further?
}
